services:
  ledger-postgres:
    image: postgres:18.4-alpine
    container_name: settleguard-ledger-dev
    env_file:
      - ../../services/ledger-service/.env
    ports:
      - "5433:5432"
    volumes:
      - ledger_dev_data:/var/lib/postgresql

  # accounts-postgres:
  #   image: postgres:18-alpine
  #   container_name: settleguard-accounts-dev
  #   env_file:
  #     - ../../services/accounts-service/.env
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - accounts_dev_data:/var/lib/postgresql

  nats:
    image: nats:2.10-alpine
    container_name: settleguard-nats-dev
    command: ["-js", "-sd", "/data"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_dev_data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  ledger_dev_data:
  # accounts_dev_data:
  nats_dev_data:
